"""
Utility script to anonymize sensitive banking data from a CSV file.

The script replaces personal identifiable information such as names, emails,
phone numbers, addresses, IBANs, card numbers, and dates of birth with
synthetic values generated by Faker. It preserves CSV headers and outputs
an anonymized file for safe analysis or sharing.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Iterable

import pandas as pd
from faker import Faker

fake = Faker("fr_FR")


SENSITIVE_FIELDS = {
    "nom": fake.last_name,
    "prenom": fake.first_name,
    "email": fake.email,
    "telephone": fake.phone_number,
    "adresse": lambda: fake.address().replace("\n", ", "),
    "iban": fake.iban,
    "date_naissance": lambda: fake.date_of_birth(minimum_age=18, maximum_age=95),
}


CARD_FIELD = "carte"


def mask_card_number(card_num: str) -> str:
    """Mask a card number while keeping the last four digits visible."""
    digits = re.sub(r"\D", "", str(card_num))
    if len(digits) <= 4:
        return "*" * len(digits)
    return "*" * (len(digits) - 4) + digits[-4:]


def anonymize_row(row: pd.Series) -> pd.Series:
    """Apply anonymization rules to a single pandas Series row."""
    result = row.copy()

    for field, generator in SENSITIVE_FIELDS.items():
        if field in result and pd.notnull(result[field]):
            result[field] = generator()

    if CARD_FIELD in result and pd.notnull(result[CARD_FIELD]):
        result[CARD_FIELD] = mask_card_number(result[CARD_FIELD])

    return result


def anonymize_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Apply anonymization to every row of a DataFrame."""
    return df.apply(anonymize_row, axis=1)


def anonymize_csv(input_csv: Path, output_csv: Path) -> None:
    """Load a CSV, anonymize it, and write the result to disk."""
    df = pd.read_csv(input_csv)
    anonymized = anonymize_dataframe(df)
    anonymized.to_csv(output_csv, index=False)


def valid_csv(path: str) -> Path:
    value = Path(path)
    if not value.is_file():
        raise argparse.ArgumentTypeError(f"{path} n'est pas un fichier valide")
    return value


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Anonymise un fichier CSV contenant des données bancaires sensibles",
    )
    parser.add_argument(
        "input_csv",
        type=valid_csv,
        help="Chemin du fichier CSV source",
    )
    parser.add_argument(
        "output_csv",
        type=Path,
        help="Chemin du fichier CSV anonymisé à produire",
    )
    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> None:
    args = parse_args(argv)
    anonymize_csv(args.input_csv, args.output_csv)
    print(f"Fichier anonymisé écrit dans : {args.output_csv}")


if __name__ == "__main__":
    main()
